import { Subject, Note, Milestone, ScheduleEvent } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'software-engineering',
    name: 'Software Engineering',
    description: 'Mastering the lifecycle of complex systems, from requirements elicitation to deployment strategies.',
    icon: 'engineering',
    notesCount: 24,
    classesCount: 12,
    color: '#bb0013',
    featured: true,
  },
  {
    id: 'front-end',
    name: 'Front-end',
    description: 'React, Tailwind, and Modern UI/UX.',
    icon: 'code',
    notesCount: 18,
    classesCount: 8,
    color: '#10b981',
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Data science and automation logic.',
    icon: 'terminal',
    notesCount: 32,
    classesCount: 14,
    color: '#f59e0b',
  },
  {
    id: 'java',
    name: 'Java',
    description: 'Object-oriented architecture.',
    icon: 'coffee',
    notesCount: 15,
    classesCount: 6,
    color: '#ef4444',
  },
  {
    id: 'database',
    name: 'Database',
    description: 'Relational modeling and SQL.',
    icon: 'database',
    notesCount: 21,
    classesCount: 9,
    color: '#3b82f6',
  },
  {
    id: 'ai-chatbot',
    name: 'IA e Chatbot',
    description: 'NLP and machine learning basics.',
    icon: 'smart_toy',
    notesCount: 12,
    classesCount: 4,
    color: '#a855f7',
  },
];

export const NOTES: Note[] = [
  {
    id: '1',
    title: 'Data Science Foundations with Pandas',
    content: 'Exploring the core functionalities of the Pandas library. Today we focused on DataFrame manipulation, handling missing values with dropna(), and performing complex aggregations using groupby functions. Significant focus on real-world dataset cleaning workflows.',
    date: 'October 24, 2024',
    tags: ['Pandas', 'Data Analysis'],
    subjectId: 'python',
  },
  {
    id: '2',
    title: 'Asynchronous Programming & Asyncio',
    content: 'Deep dive into the Event Loop architecture. We implemented concurrent network requests using aiohttp and compared execution times against synchronous requests. Understanding await, async, and Task objects is crucial for high-performance backend systems.',
    date: 'October 21, 2024',
    tags: ['Asyncio', 'Performance'],
    subjectId: 'python',
  },
  {
    id: '3',
    title: 'Advanced Decorators and Closures',
    content: 'Conceptualizing decorators as higher-order functions. Practical application in logging and authentication middleware. Discussed functools.wraps importance in maintaining function metadata. Code challenge: writing a memoization decorator from scratch.',
    date: 'October 18, 2024',
    tags: ['Decorators', 'Intermediate'],
    subjectId: 'python',
  },
];

export const MILESTONE: Milestone = {
  id: '1',
  title: 'Challenge Sprint 2 Presentation',
  description: "Your team presentation is scheduled for next Monday. Ensure all documentation in the 'Software Engineering' folder is updated.",
  daysLeft: 4,
  category: 'Next Milestone',
};

export const SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: '1',
    title: 'Software Engineering Lecture',
    time: '08:00',
    duration: '2h',
    subjectId: 'software-engineering',
    type: 'lecture',
    day: 'Monday',
  },
  {
    id: '2',
    title: 'Database Lab',
    time: '10:00',
    duration: '1h 30m',
    subjectId: 'database',
    type: 'lab',
    day: 'Monday',
  },
  {
    id: '3',
    title: 'Python for Data Science',
    time: '14:00',
    duration: '2h',
    subjectId: 'python',
    type: 'lecture',
    day: 'Tuesday',
  },
  {
    id: '4',
    title: 'Front-end Workshop',
    time: '09:00',
    duration: '3h',
    subjectId: 'front-end',
    type: 'lab',
    day: 'Wednesday',
  },
  {
    id: '5',
    title: 'Java Architecture',
    time: '11:00',
    duration: '2h',
    subjectId: 'java',
    type: 'lecture',
    day: 'Thursday',
  },
  {
    id: '6',
    title: 'AI & Chatbot Seminar',
    time: '15:00',
    duration: '1h 30m',
    subjectId: 'ai-chatbot',
    type: 'presentation',
    day: 'Friday',
  },
];
