import { Subject, Note, Milestone, ScheduleEvent } from './types';

export const SUBJECTS: Subject[] = [
  {
    id: 'software-engineering',
    name: 'Software Engineering',
    description: 'Mastering the lifecycle of complex systems, from requirements elicitation to deployment strategies.',
    icon: 'engineering',
    notesCount: 24,
    classesCount: 12,
    color: '#bb0013',
    featured: true,
  },
  {
    id: 'front-end',
    name: 'Front-end',
    description: 'React, Tailwind, and Modern UI/UX.',
    icon: 'code',
    notesCount: 18,
    classesCount: 8,
    color: '#10b981',
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Data science and automation logic.',
    icon: 'terminal',
    notesCount: 32,
    classesCount: 14,
    color: '#f59e0b',
  },
  {
    id: 'java',
    name: 'Java',
    description: 'Object-oriented architecture.',
    icon: 'coffee',
    notesCount: 15,
    classesCount: 6,
    color: '#ef4444',
  },
  {
    id: 'database',
    name: 'Database',
    description: 'Relational modeling and SQL.',
    icon: 'database',
    notesCount: 21,
    classesCount: 9,
    color: '#3b82f6',
  },
  {
    id: 'ai-chatbot',
    name: 'IA e Chatbot',
    description: 'NLP and machine learning basics.',
    icon: 'smart_toy',
    notesCount: 12,
    classesCount: 4,
    color: '#a855f7',
  },
];

export const NOTES: Note[] = [
  {
    id: '1',
    title: 'Data Science Foundations with Pandas',
    content: 'Exploring the core functionalities of the Pandas library. Today we focused on DataFrame manipulation, handling missing values with dropna(), and performing complex aggregations using groupby functions. Significant focus on real-world dataset cleaning workflows.',
    date: 'October 24, 2024',
    tags: ['Pandas', 'Data Analysis'],
    subjectId: 'python',
  },
  {
    id: '2',
    title: 'Asynchronous Programming & Asyncio',
    content: 'Deep dive into the Event Loop architecture. We implemented concurrent network requests using aiohttp and compared execution times against synchronous requests. Understanding await, async, and Task objects is crucial for high-performance backend systems.',
    date: 'October 21, 2024',
    tags: ['Asyncio', 'Performance'],
    subjectId: 'python',
  },
  {
    id: '3',
    title: 'Advanced Decorators and Closures',
    content: 'Conceptualizing decorators as higher-order functions. Practical application in logging and authentication middleware. Discussed functools.wraps importance in maintaining function metadata. Code challenge: writing a memoization decorator from scratch.',
    date: 'October 18, 2024',
    tags: ['Decorators', 'Intermediate'],
    subjectId: 'python',
  },
];

export const MILESTONE: Milestone = {
  id: '1',
  title: 'Challenge Sprint 2 Presentation',
  description: "Your team presentation is scheduled for next Monday. Ensure all documentation in the 'Software Engineering' folder is updated.",
  daysLeft: 4,
  category: 'Next Milestone',
};

export const SCHEDULE_EVENTS: ScheduleEvent[] = [
  {
    id: '1',
    title: 'Software Engineering Lecture',
    time: '19:00',
    duration: '2h',
    description: 'Mastering software design patterns and architectural principles for scalable systems.',
    subjectId: 'software-engineering',
    type: 'lecture',
    day: 'Monday',
    isOnline: false,
  },
  {
    id: '2',
    title: 'Database Lab',
    time: '21:15',
    duration: '2h',
    description: 'Hands-on practice with SQL queries, normalization, and relational model design.',
    subjectId: 'database',
    type: 'lab',
    day: 'Monday',
    isOnline: false,
  },
  {
    id: '3',
    title: 'Python for Data Science',
    time: '19:00',
    duration: '2h',
    description: 'Advanced data manipulation using Pandas and NumPy libraries - ONLINE CLASS',
    subjectId: 'python',
    type: 'lecture',
    day: 'Tuesday',
    isOnline: true,
  },
  {
    id: '4',
    title: 'Front-end Concepts',
    time: '21:15',
    duration: '2h',
    description: 'React hooks, state management, and component lifecycle understanding.',
    subjectId: 'front-end',
    type: 'lecture',
    day: 'Tuesday',
    isOnline: true,
  },
  {
    id: '5',
    title: 'Front-end Workshop',
    time: '19:00',
    duration: '2h',
    description: 'Building responsive UI components with Tailwind CSS and Material Design principles.',
    subjectId: 'front-end',
    type: 'lab',
    day: 'Wednesday',
    isOnline: false,
  },
  {
    id: '6',
    title: 'Java Architecture',
    time: '21:15',
    duration: '2h',
    description: 'Object-oriented design patterns, SOLID principles, and enterprise architecture.',
    subjectId: 'java',
    type: 'lecture',
    day: 'Wednesday',
    isOnline: false,
  },
  {
    id: '7',
    title: 'IA & Machine Learning',
    time: '19:00',
    duration: '2h',
    description: 'fundamentals of neural networks and practical ML implementation.',
    subjectId: 'ai-chatbot',
    type: 'lecture',
    day: 'Thursday',
    isOnline: false,
  },
  {
    id: '8',
    title: 'Software Engineering Seminar',
    time: '21:15',
    duration: '2h',
    description: 'Discussion on agile methodologies, DevOps practices, and continuous integration.',
    subjectId: 'software-engineering',
    type: 'presentation',
    day: 'Thursday',
    isOnline: false,
  },
  {
    id: '9',
    title: 'AI & Chatbot Seminar',
    time: '19:00',
    duration: '2h',
    description: 'Building chatbots with NLP, conversational AI, and language models - ONLINE CLASS',
    subjectId: 'ai-chatbot',
    type: 'presentation',
    day: 'Friday',
    isOnline: true,
  },
  {
    id: '10',
    title: 'Database Advanced Topics',
    time: '21:15',
    duration: '2h',
    description: 'NoSQL databases, indexing strategies, and query optimization - ONLINE CLASS',
    subjectId: 'database',
    type: 'lecture',
    day: 'Friday',
    isOnline: true,
  },
];
